
app:
  aws:
    cognito:
      clientId: ${COGNITO_CLIENT_ID}
      clientSecret: ${COGNITO_CLIENT_SECRET}
  services:
    frontend: ${FRONTEND_SERVICE}
    backend:
      - name: job
        url: ${JOB_SERVICE}
      - name: user
        url: ${USER_SERVICE}
