apiVersion: v1
kind: Namespace
metadata:
  name: sj-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sj-ns
  name: sj-bff
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sj-bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sj-bff
    spec:
      containers:
        - name: sj-bff
          image: ${IMAGE_NAME}
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
