apiVersion: v1
kind: Namespace
metadata:
  name: sj-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: sj-ns
  name: sj-bff
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: sj-bff
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sj-bff
    spec:
      containers:
        - name: sj-bff
          image: ${IMAGE_NAME}
          resources:
            requests:
              memory: 256Mi
              cpu: 150m
            limits:
              memory: 256Mi
              cpu: 150m
          env:
            - name: COGNITO_CLIENT_ID
              value: ${COGNITO_CLIENT_ID}

            - name: COGNITO_CLIENT_SECRET
              value: ${COGNITO_CLIENT_SECRET}

            - name: FRONTEND_SERVICE
              value: ${FRONTEND_URL}

            - name: JOB_SERVICE
              value: ${JOB_SERVICE_URL}

            - name: USER_SERVICE
              value: ${USER_SERVICE_URL}

          imagePullPolicy: Always
          ports:
            - containerPort: 8080
