apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sj-bff-autoscaling
  namespace: sj-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sj-bff
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80

