apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sj-bff-autoscaling
  namespace: sj-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sj-bff
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 10
#    - type: Resource
#      resource:
#        name: memory
#        target:
#          type: AverageValue
#          averageValue: 10Mi

